compilation:
  cloud_properties:
    name: random
  network: kafka1
  reuse_compilation_vms: true
  workers: 6

director_uuid: c5f8d0da-f8ac-4918-a1a3-0a846fb97d09

jobs:
- instances: 2
  name: kafka_z1
  networks:
  - name: kafka1
    static_ips: null
  properties:
    kafka:
      zookeeper:
        connect: 10.244.2.42:2181,10.244.2.46:2181,10.244.2.50:2181
  resource_pool: small_z1
  template: kafka
  persistent_disk: 5120
  update:
    canaries: 10
meta:
  environment: kafka-warden
  stemcell:
    name: bosh-warden-boshlite-ubuntu-lucid-go_agent
    version: latest
name: kafka-warden
networks:
- name: kafka1
  subnets:

  # Assumes 1 static vm
  - cloud_properties:
      name: random
    range: 10.244.3.0/30
    reserved:
    - 10.244.3.1
    static:
    - 10.244.3.2

  # Assumes 4 dynamic vm
  - cloud_properties:
      name: random
    range: 10.244.3.4/30
    reserved:
    - 10.244.3.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.8/30
    reserved:
    - 10.244.3.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.12/30
    reserved:
    - 10.244.3.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.16/30
    reserved:
    - 10.244.3.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.3.20/30
    reserved:
    - 10.244.3.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.24/30
    reserved:
    - 10.244.3.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.28/30
    reserved:
    - 10.244.3.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.32/30
    reserved:
    - 10.244.3.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.36/30
    reserved:
    - 10.244.3.37
    static: []

properties: {}
releases:
- name: kafka.hybris.dev
  version: latest
resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: kafka1
  size: 3
  stemcell:
    name: bosh-warden-boshlite-ubuntu-lucid-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000
