---
packages:
- name: kafka
  version: !binary |-
    YTYyNDAzYzgwOTFkZTkyMzhhY2ZhMjYwOWFlZDBmOTFhODg5MjU5Ng==
  sha1: !binary |-
    NmE0YmRlYTMxMWQ3YWI4NWU2NjA4ODhhMjA5MTk4ZGVhMzc1ZDg5NQ==
  fingerprint: !binary |-
    YTYyNDAzYzgwOTFkZTkyMzhhY2ZhMjYwOWFlZDBmOTFhODg5MjU5Ng==
  dependencies:
  - java7
- name: java7
  version: !binary |-
    MjFhOGQyZWFiMjkyODFkZGU2ZTk3NjNiM2EzNDE1Y2M4Mzc2ZWY0Ng==
  sha1: !binary |-
    YThkYTRhOTU4M2IzZmEwYTMzYjIyY2UxY2M1YmI2Y2E2ZjAzZjg0Nw==
  fingerprint: !binary |-
    MjFhOGQyZWFiMjkyODFkZGU2ZTk3NjNiM2EzNDE1Y2M4Mzc2ZWY0Ng==
  dependencies: []
jobs:
- name: kafka
  version: !binary |-
    ZDZiNTRlZTAyZTkwMDIyZGQ3MzU0NzMwNGE4MTgyNGMzMWJlOTU4ZQ==
  fingerprint: !binary |-
    ZDZiNTRlZTAyZTkwMDIyZGQ3MzU0NzMwNGE4MTgyNGMzMWJlOTU4ZQ==
  sha1: !binary |-
    ZTZiNTk4MjEzYjE2NTljMjdlNGYyMDIwMzVkYzEyMzlhZDQzNDQ2Zg==
commit_hash: 6ae0b4a4
uncommitted_changes: false
name: kafka-hybris
version: 2
