meta:
  environment: kafka-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: kafka
    networks:
      - name: kafka1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: kafka1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.11.0/30
    reserved:
    - 10.244.11.1
    static:
    - 10.244.11.2

  - cloud_properties:
      name: random
    range: 10.244.11.4/30
    reserved:
    - 10.244.11.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.11.8/30
    reserved:
    - 10.244.11.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.11.12/30
    reserved:
    - 10.244.11.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.11.16/30
    reserved:
    - 10.244.11.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.11.20/30
    reserved:
    - 10.244.11.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.11.24/30
    reserved:
    - 10.244.11.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.11.28/30
    reserved:
    - 10.244.11.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.11.32/30
    reserved:
    - 10.244.11.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.11.36/30
    reserved:
    - 10.244.11.37
    static: []
